### ISSUE TITLE
Bug: pools.get_pool_by_id(pool_id) function works only for some pools, but not all of them.

### ISSUE THREAD

**Issue by SpawnDev** [theeldermillenial/minswap-py#12]
```
from minswap import assets, pools

pool_ids = ["63f2cbfa5bf8b68828839a2575c8c70f14a32f50ebbfa7c654043269793be896", # SNEK - OK
            "8fde43a3f0b9f0e6f63bec7335e0b855c6b62a4dc51f1b762ccb6dfbbafcfe47", # iUSD - OK
            "d8c9db5805c51ff35642da3a54c29e573f747461d91d010125683494537debf8", # HUNT - Bad
            "f9d754bbb359e164ac964df47e84726b33117c59eb57e90f835ac6027af0f3f2", # JPG - Bad
            "4705d99a4cf6bce9181e60fdbbf961edf6acad7141ed69186c8a8883600e59c5", # GENS - Bad
            "178d9b1934c022ded69fe43a30fdb05e1b7dbccbd6dc359708da68dfa6b4a4c3", # SMOKES - Bad
            "93f16d92eb096ffa4b604d8f61fce105987dd04148c2ce563f9c3f2017f0c4f2",]# CSWAP - Bad

for pool_id in pool_ids:
    try:
        info = pools.get_pool_by_id(pool_id)
        print(info)
        print(info.asset_b_name + "\n")
    except Exception as e:
        print("Error: " + str(e) + "\n")
```

I tried to get pool info for top 100 coins, but the function failed for 5 of them. This function prints out asset name for pools, and raises exception if it fails. Exception is found for 5/7 of them, and can be either (Workaround can be found using "pool.unit_b" attribute):
``` Error: 'utf-8' codec can't decode byte 0xdf in position 2: invalid continuation byte ```
or (No workaround):
``` Error: 'NoneType' object has no attribute 'asset_b_name' ```

Moreover, pools.get_pools() function does NOT return all pools, and does not return same pools that failed previously. This could be a clue to where the bug happens.

Additional info:
- I tried adding "update_cache=True" to function, no help.
- I tested it with official minswap-sdk written in Javascript, and it works as intended.

**Comment by SpawnDev** [comment]
I analyzed top 100 trading pairs (by TVL) on minswap, and found 5 pools that are not indexed.
```
# Asset_name, Asset_id
missing_pools = [["JPG", "681b5d0383ac3b457e1bcc453223c90ccef26b234328f45fa10fd276"],
                ["HUNT", "95a427e384527065f2f8946f5e86320d0117839a5e98ea2c0b55fb00"],
                ["CSWAP", "bf524874448cbf52be3a26133b0a0edf5eb65c09ffed383b881ad327"],
                ["FACT", "a3931691f5c4e65d01c429e473d0dd24c51afdb6daf88e632a6c1e51"],
                ["VINCE", "17d52137068ea7938fc04ad5e5eebd26a2344aec587ab622a6ff8227"]]
```
They are stored on less popular minswap pool addresses:
```
# Asset_name, Minswap_pool_id, Address_UTXOs
missing_pool_adds = [["JPG", "addr1z8snz7c4974vzdpxu65ruphl3zjdvtxw8strf2c2tmqnxzfpahn0eymy6pz4yr4mvptlpjv9eh2swz0u0hjj4qp439kq4064e4", 10],
                ["HUNT", "addr1z8snz7c4974vzdpxu65ruphl3zjdvtxw8strf2c2tmqnxzfexpwjxduemhljcrgp4sn8zl3udcljp5w0027g06ygw09s9y05av", 6],
                ["CSWAP", "addr1z8snz7c4974vzdpxu65ruphl3zjdvtxw8strf2c2tmqnxzv8exr5lcrw7m4cups4lw0yuc4tp40skfnzlr94fndwdsfsatrhh6", 5],
                ["FACT", "addr1z8snz7c4974vzdpxu65ruphl3zjdvtxw8strf2c2tmqnxzf6g882n6sa2gxnk42heavu7uddl5jdl0ektf5f204mmc7s3ykuf9", 8],
                ["VINCE", "addr1z8snz7c4974vzdpxu65ruphl3zjdvtxw8strf2c2tmqnxzgyqjr3j8kwe05hu3xlkm4pw49engd8hajl34c8zgljqwks23umps", 5]]
```

Furthermore, all of these coins are relatively new to Minswap. Oldest LP was created in mid-September, which makes me suspicious of yet another caching issue.

If you try to retrieve UTXO's from these "Minswap_pool_id"s, and look for assets, you will clearly see all of these coins being there, however, minswap.pools.get_pools() function is totally oblivious to them.

**Comment by theeldermillenial** [comment]
Hm...interesting. I'll look into this. In the most recent version I thought I had fixed this issue forever by looking for all addresses that have the Minswap NFT.

What version of `minswap-py` are you using?

**Comment by SpawnDev** [comment]
Yeah, I was on v0.3.1 whole time. Haven't noticed it was updated.

Great, thanks!
